--- #YAML:1.0
name:               Email-MIME
version:            1.904
abstract:           ~
author:  []
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Email::MessageID:     0
    Email::MIME::ContentType:  1.011
    Email::MIME::Encodings:  1.313
    Email::Simple:        2.004
    Email::Simple::Creator:  0
    Encode:               1.9801
    MIME::Types:          1.13
    Test::More:           0.47
resources:
    repository:  http://github.com/rjbs/email-mime
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
