--- #YAML:1.0
name:                Email-MIME
version:             1.857
abstract:            ~
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
    Email::MIME::ContentType:      1.011
    Email::MIME::Encodings:        1.3
    Email::Simple:                 1.995
    Encode:                        1.9801
    MIME::Types:                   1.13
    Test::More:                    0.47
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
